In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("C:\\Users\\pc\\Desktop\\Rade\\kata_test\\train.csv")
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [29]:
# Veličina populacije
N = len(df)
print("Populacija ima", N, "jedinica")

# Iz skupa isključujemo gde je širina ekrana 0
df = df.query('sc_w != 0')
N = len(df)
print("Populacija nakon isključenja telefona koji imaju širinu ekrana 0 ima", N, "jedinica")

# Prikaz različitih vrednosti u koloni "price_range"
razlicite_vrednosti = df['price_range'].unique()
print("Različite vrednosti u koloni price_range:", razlicite_vrednosti)

# Izmjena naziva vrednosti price_range kolone
df['price_range'] = df['price_range'].astype(str) # prvo pretvaranje u tekstualni tip podatka
df.loc[df['price_range'] == "0", 'price_range'] = 'niska_cena'
df.loc[df['price_range'] == "1", 'price_range'] = 'srednja_niska_cena'
df.loc[df['price_range'] == "2", 'price_range'] = 'srednja_visoka_cena'
df.loc[df['price_range'] == "3", 'price_range'] = 'visoka_cena'

Populacija ima 1820 jedinica
Populacija nakon isključenja telefona koji imaju širinu ekrana 0 ima 1820 jedinica
Različite vrednosti u koloni price_range: ['srednja_niska_cena' 'srednja_visoka_cena' 'visoka_cena' 'niska_cena']

In [47]:
# Računanje procentualnog učešća različitih vrednosti price_range kolone
broj_jedinica_po_stratumima = df['price_range'].value_counts()
print("Broj jedinica po različitim stratumima:", broj_jedinica_po_stratumima)
print("\n") # prazan red

# Broj jedinica po stratumima izdvojen u varijable iz broj_jedinica_po_stratumima
ukupno_telefona_niska_cena =  broj_jedinica_po_stratumima["niska_cena"]
ukupno_telefona_srednja_niska_cena =  broj_jedinica_po_stratumima["srednja_niska_cena"]
ukupno_telefona_srednja_visoka_cena =  broj_jedinica_po_stratumima["srednja_visoka_cena"]
ukupno_telefona_visoka_cena =  broj_jedinica_po_stratumima["visoka_cena"]

print("Ukupno telefona niska_cena:", ukupno_telefona_niska_cena)
print("Ukupno telefona srednja_niska_cena:", ukupno_telefona_srednja_niska_cena)
print("Ukupno telefona srednja_visoka_cena:", ukupno_telefona_srednja_visoka_cena)
print("Ukupno telefona visoka_cena:", ukupno_telefona_visoka_cena)

# Udio svakog stratuma u populaciji
niska_cena_udio = round(ukupno_telefona_niska_cena/N,2)
srednja_niska_cena_udio = round(ukupno_telefona_srednja_niska_cena/N,2)
srednja_visoka_cena_udio = round(ukupno_telefona_srednja_visoka_cena/N,2)
visoka_cena_udio = round(ukupno_telefona_visoka_cena/N,2)

print("\n")
print("Udio niska_cena u populaciji:",niska_cena_udio)
print("Udio srednja_niska_cena u populaciji:",srednja_niska_cena_udio)
print("Udio srednja_visoka_cena u populaciji:",srednja_visoka_cena_udio)
print("Udio visoka_cena u populaciji:",visoka_cena_udio)

print("Ukupno", niska_cena_udio + srednja_niska_cena_udio + srednja_visoka_cena_udio + visoka_cena_udio)
print("\n")

Broj jedinica po različitim stratumima: price_range
visoka_cena            461
srednja_visoka_cena    456
srednja_niska_cena     452
niska_cena             451
Name: count, dtype: int64


Ukupno telefona niska_cena: 451
Ukupno telefona srednja_niska_cena: 452
Ukupno telefona srednja_visoka_cena: 456
Ukupno telefona visoka_cena: 461


Udio niska_cena u populaciji: 0.25
Udio srednja_niska_cena u populaciji: 0.25
Udio srednja_visoka_cena u populaciji: 0.25
Udio visoka_cena u populaciji: 0.25
Ukupno 1.0

In [46]:
# Računanje broja jedinica svakog stratuma u uzorku
n = 100

broj_jedinica_niska_cena_u_uzorku = round(n * niska_cena_udio)
print("Broj jedinica stratuma niska_cena u uzorku:", broj_jedinica_niska_cena_u_uzorku)

broj_jedinica_srednja_niska_cena_u_uzorku = round(n * srednja_niska_cena_udio)
print("Broj jedinica stratuma srednja_niska_cena u uzorku:", broj_jedinica_srednja_niska_cena_u_uzorku)

broj_jedinica_srednja_visoka_cena_u_uzorku = round(n * srednja_visoka_cena_udio)
print("Broj jedinica stratuma srednja_visoka_cena_udio u uzorku:", broj_jedinica_srednja_visoka_cena_u_uzorku)

broj_jedinica_visoka_cena_u_uzorku = round(n * visoka_cena_udio)
print("Broj jedinica stratuma visoka_cena u uzorku:", broj_jedinica_visoka_cena_u_uzorku)

Broj jedinica stratuma niska_cena u uzorku: 25
Broj jedinica stratuma srednja_niska_cena u uzorku: 25
Broj jedinica stratuma srednja_visoka_cena_udio u uzorku: 25
Broj jedinica stratuma visoka_cena u uzorku: 25

In [54]:
# Formiranje stratuma iz populacije 

df_niska_cena_stratum = df[df['price_range'] == "niska_cena"] # iz populacije izvlači samo one sa niskom cenom 
df_srednja_niska_cena_stratum = df[df['price_range'] == "srednja_niska_cena"] 
df_srednja_visoka_cena_stratum = df[df['price_range'] == "srednja_visoka_cena"] 
df_visoka_cena_stratum = df[df['price_range'] == "visoka_cena"]

In [56]:
# Uzimanje slučajnih jedinica iz svakog pojedinačnog stratuma

df_slucajni_uzorak_niska_cena = df_niska_cena_stratum.sample(n=broj_jedinica_niska_cena_u_uzorku)  
df_slucajni_uzorak_srednja_niska_cena = df_srednja_niska_cena_stratum.sample(n=broj_jedinica_srednja_niska_cena_u_uzorku)  
df_slucajni_uzorak_srednja_visoka_cena = df_srednja_visoka_cena_stratum.sample(n=broj_jedinica_srednja_visoka_cena_u_uzorku)  
df_slucajni_uzorak_visoka_cena = df_visoka_cena_stratum.sample(n=broj_jedinica_visoka_cena_u_uzorku)  

df_uzorak = pd.concat([df_slucajni_uzorak_niska_cena, df_slucajni_uzorak_srednja_niska_cena, df_slucajni_uzorak_srednja_visoka_cena, df_slucajni_uzorak_visoka_cena], ignore_index=True)
# ignore_index=True - ovo znači ponovno postavljanje indexa